"""Module that lists the species_configs."""

SPECIES_CONFIGS_EXCL_GASBOX = [
    "tropospheric_adjustment",
    "forcing_efficacy",
    "forcing_temperature_feedback",
    "forcing_scale",
    "molecular_weight",
    "baseline_concentration",
    "forcing_scale",
    "forcing_reference_concentration",
    "iirf_0",
    "iirf_airborne",
    "iirf_uptake",
    "iirf_temperature",
    "baseline_emissions",
    "g0",
    "g1",
    "greenhouse_gas_radiative_efficiency",
    "contrails_radiative_efficiency",
    "erfari_radiative_efficiency",
    "h2o_stratospheric_factor",
    "lapsi_radiative_efficiency",
    "land_use_cumulative_emissions_to_forcing",
    "ozone_radiative_efficiency",
    "cl_atoms",
    "br_atoms",
    "fractional_release",
    "ch4_lifetime_chemical_sensitivity",
    "aci_shape",
]
